#!/bin/bash
#####################
#step 1: trimmomatic
#####################

#load the module

source /opt/asn/etc/asn-bash-profiles-special/modules.sh
module load trimmomatic


for i in ct12c2 ct12c3 ct12c4 ct12v2 ct12v3 ct12v4 ct24c1 ct24c3 ct24c4 ct24v1 ct24v2 ct24v3 ct48c1 ct48c5 ct48c6 ct48v4 ct48v5 ct48v6 hg12c3 hg12c4 hg12c5 hg12v2 hg12v4 hg12v5 hg24c2 hg24c4 hg24c5 hg24v1 hg24v4 hg24v6 hg48c2 hg48c3 hg48c4 hg48v2 hg48v3 hg48v7 sp12c1 sp12c4 sp24c1 sp24c2 sp24v1 sp24v2 sp24v4 sp48v3 tr12c1 tr12c4 tr12c5 tr12v2 tr12v4 tr24v4 tr24v7 tr48c2 tr48c5 tr48v2 tr48v3 tr48v4 
do
        cd ${i} #folders are named according to sample names
        java -jar /mnt/beegfs/apps/dmc/apps/spack_0.16.0/spack/opt/spack/linux-centos7-ivybridge/gcc-10.2.0/trimmomatic-0.39-ili2pw5eux5c4zkvobobylopjwwu7phd/bin/trimmomatic-0.39.jar PE ${i}_1.fq.gz ${i}_2.fq.gz output_forward_paired_${i}.fq.gz output_forward_unpaired_${i}.fq.gz output_reverse_paired_${i}${j}.fq.gz output_reverse_unpaired_${i}.fq.gz ILLUMINACLIP:TruSeq3-PE.fa:2:30:10:2:True LEADING:3 TRAILING:3 MINLEN:36
        cd ..
done

#for 3 samples:
####################################################################
#         Alabama Supercomputer Center - SLURM Epilog
# Your username for this job is:              aubrxh001
# Your account for this job is:               users
# Your group for this job is:                 aubpathbio
# Your job ID is:                             954469
# Your job name is:                           taxshSCRIPT
# Your partition for this job is:             dmc
# Your architecture for this job is:          ivy
# Your job submit QOS is:                     small
# Your job ran on nodes:                      dmc22
# Your number of processors used:             4
# Your job was submitted at:                  2023-03-02T14:36:20
# Your job started at:                        2023-03-02T14:36:26
# Your job ended at:                          2023-03-02T15:38:47
# Your job elapsed time is:                   01:02:21
# Your job dedicated time is:                 04:09:24
# Your requested wall time is:                05:00:00
# Your job cpu parallel efficiency is:        51.48%
# Your requested memory is:                   1000M
# Your max memory used:                       215428K
# Your job memory efficiency is:              21.04%
# Your job state is:                          COMPLETED
# Your job exit code is:                      0:0
# Your requested resource was:                cpu=4,mem=1000M,node=1
# Your job commercial value is:               $ 2.494
####################################################################



##########################
# step 2: delete and move
##########################

# delete raw files and move Trimmomatic files to main folder
# folders are named according to sample names

for i in ct12c2 ct12c3 ct12c4 ct12v2 ct12v3 ct12v4 ct24c1 ct24c3 ct24c4 ct24v1 ct24v2 ct24v3 ct48c1 ct48c5 ct48c6 ct48v4 ct48v5 ct48v6 hg12c3 hg12c4 hg12c5 hg12v2 hg12v4 hg12v5 hg24c2 hg24c4 hg24c5 hg24v1 hg24v4 hg24v6 hg48c2 hg48c3 hg48c4 hg48v2 hg48v3 hg48v7 sp12c1 sp12c4 sp24c1 sp24c2 sp24v1 sp24v2 sp24v4 sp48v3 tr12c1 tr12c4 tr12c5 tr12v2 tr12v4 tr24v4 tr24v7 tr48c2 tr48c5 tr48v2 tr48v3 tr48v4 
do
               cd ${i}
               #rm ${i}_1.fq.gz
               #rm ${i}_2.fq.gz
               mv output_reverse_paired_${i}.fq.gz ..
               mv output_forward_paired_${i}.fq.gz ..
               cd ..
done
