#!/bin/bash
#
#  load the module
source /opt/asn/etc/asn-bash-profiles-special/modules.sh
module load anaconda/3-2019.10
module load samtools/1.13
#
samtools sort -o ct12c2.bam ct12c2.sam
samtools sort -o ct12c3.bam ct12c3.sam
samtools sort -o ct12c4.bam ct12c4.sam
samtools sort -o ct12v2.bam ct12v2.sam
samtools sort -o ct12v3.bam ct12v3.sam
samtools sort -o ct12v4.bam ct12v4.sam
