#!/bin/bash
#
#  load the module
source /opt/asn/etc/asn-bash-profiles-special/modules.sh
module load stringtie/2.2.1
#
#
stringtie -e -B -G ncbi-index/galgal_ncbi.gtf -o output/ct12c2/ct12c2.gtf ct12c2.bam
stringtie -e -B -G ncbi-index/galgal_ncbi.gtf -o output/ct12c3/ct12c3.gtf ct12c3.bam
stringtie -e -B -G ncbi-index/galgal_ncbi.gtf -o output/ct12c4/ct12c4.gtf ct12c4.bam
stringtie -e -B -G ncbi-index/galgal_ncbi.gtf -o output/ct12v2/ct12v2.gtf ct12v2.bam
stringtie -e -B -G ncbi-index/galgal_ncbi.gtf -o output/ct12v3/ct12v3.gtf ct12v3.bam
stringtie -e -B -G ncbi-index/galgal_ncbi.gtf -o output/ct12v4/ct12v4.gtf ct12v4.bam

#for 1 sample
####################################################################
#         Alabama Supercomputer Center - SLURM Epilog
# Your username for this job is:              aubrxh001
# Your account for this job is:               users
# Your group for this job is:                 aubpathbio
# Your job ID is:                             903309
# Your job name is:                           string4shSCRIPT
# Your partition for this job is:             dmc
# Your architecture for this job is:          ivy
# Your job submit QOS is:                     small
# Your job ran on nodes:                      dmc24
# Your number of processors used:             1
# Your job was submitted at:                  2022-12-06T17:14:02
# Your job started at:                        2022-12-06T17:14:18
# Your job ended at:                          2022-12-06T17:17:31
# Your job elapsed time is:                   00:03:13
# Your job dedicated time is:                 00:03:13
# Your requested wall time is:                01:00:00
# Your job cpu parallel efficiency is:        89.12%
# Your requested memory is:                   2000M
# Your max memory used:                       323568K
# Your job memory efficiency is:              15.80%
# Your job state is:                          COMPLETED
# Your job exit code is:                      0:0
# Your requested resource was:                cpu=1,mem=2000M,node=1
# Your job commercial value is:               $ 0.00804167
####################################################################
